// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvpCVYmcWmzlYeiwZULC_nwtguc80Sc8c',
    appId: '1:857644343778:web:ec5bbf3e4c2478454b59bb',
    messagingSenderId: '857644343778',
    projectId: 'kuaforapp12345',
    authDomain: 'kuaforapp12345.firebaseapp.com',
    storageBucket: 'kuaforapp12345.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACvVQtCxQTvJ169pA50mC3Ibtt53S6WNw',
    appId: '1:857644343778:android:08d3e955827bdf604b59bb',
    messagingSenderId: '857644343778',
    projectId: 'kuaforapp12345',
    storageBucket: 'kuaforapp12345.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuTRLDfzPUpSAFdrBX84_3U4jQoa0z0aA',
    appId: '1:857644343778:ios:02c92730b57187a44b59bb',
    messagingSenderId: '857644343778',
    projectId: 'kuaforapp12345',
    storageBucket: 'kuaforapp12345.firebasestorage.app',
    iosBundleId: 'com.example.kuaforApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuTRLDfzPUpSAFdrBX84_3U4jQoa0z0aA',
    appId: '1:857644343778:ios:02c92730b57187a44b59bb',
    messagingSenderId: '857644343778',
    projectId: 'kuaforapp12345',
    storageBucket: 'kuaforapp12345.firebasestorage.app',
    iosBundleId: 'com.example.kuaforApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvpCVYmcWmzlYeiwZULC_nwtguc80Sc8c',
    appId: '1:857644343778:web:c62f34f8c84958e64b59bb',
    messagingSenderId: '857644343778',
    projectId: 'kuaforapp12345',
    authDomain: 'kuaforapp12345.firebaseapp.com',
    storageBucket: 'kuaforapp12345.firebasestorage.app',
  );
}
